spring:
  profiles:
    active: dev

  application:
    name: mople

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  tomcat:
    max-http-form-post-size: 30MB

logging:
  level:
    com.groupMeeting.global.client: DEBUG
