spring:
  profiles:
    active: dev

  application:
    name: mople

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  tomcat:
    max-http-form-post-size: 30MB

logging:
  thresholds:
    slow:
      api: 3000
      query: 1000